language: minimal

services:
  - docker

before_install:
  - docker build -t my_service:latest .

script:
  - docker run -d --name my_service_container -p 8000:8000 my_service:latest
  - docker ps | grep my_service_container
  # Adicione comandos para executar testes no seu projeto, se necessário

after_script:
  - docker stop my_service_container
  - docker rm my_service_container
